export const NIFTY50 = [
  'RELIANCE','TCS','HDFCBANK','INFY','ICICIBANK','HINDUNILVR','ITC',
  'KOTAKBANK','LT','AXISBANK','BHARTIARTL','SBIN','BAJFINANCE',
  'ASIANPAINT','MARUTI','HCLTECH','SUNPHARMA','TITAN','ULTRACEMCO',
  'WIPRO','ONGC','POWERGRID','NTPC','TECHM','ADANIENT','ADANIPORTS',
  'TATASTEEL','JSWSTEEL','COALINDIA','DIVISLAB','DRREDDY','CIPLA',
  'APOLLOHOSP','BAJAJFINSV','BAJAJ-AUTO','EICHERMOT','HEROMOTOCO',
  'M&M','BPCL','HINDALCO','GRASIM','INDUSINDBK','NESTLEIND','TATACONSUM',
  'SHRIRAMFIN','BEL','TRENT','ETERNAL','SBILIFE',
];

export const NIFTY_NEXT50 = [
  'ADANIGREEN','ADANIPOWER','AMBUJACEM','BANKBARODA','BERGEPAINT',
  'BOSCHLTD','BRITANNIA','CANBK','CHOLAFIN','COLPAL','DABUR','DLF',
  'GODREJCP','GODREJPROP','HAVELLS','ICICIPRULI','ICICIGI','INDUSTOWER',
  'IOC','IRFC','JINDALSTEL','LODHA','LTTS','LUPIN','MARICO','NHPC',
  'OBEROIRLTY','OFSS','PAGEIND','PIDILITIND','PNB','SBICARD','SIEMENS',
  'TORNTPHARM','TVSMOTOR','UNIONBANK','UPL','VEDL','VOLTAS','ZYDUSLIFE',
  'SAIL','MUTHOOTFIN',
];

export const NIFTY_MIDCAP = [
  'ABCAPITAL','ABFRL','AUBANK','AUROPHARMA','BALKRISIND','BANDHANBNK',
  'BATAINDIA','BHEL','BIOCON','BSE','CAMS','CANFINHOME','CGPOWER',
  'CONCOR','CUMMINSIND','DEEPAKNTR','DELHIVERY','ESCORTS','EXIDEIND',
  'FEDERALBNK','FORTIS','GAIL','GMRAIRPORT','GNFC','GODREJIND',
  'HINDCOPPER','HINDPETRO','HONASA','IDFCFIRSTB','IEX','INDIGO','INDHOTEL',
  'JKCEMENT','JSL','JUBLFOOD','KAJARIACER','KPITTECH','LICHSGFIN','LICI',
  'MAXHEALTH','MCX','MFSL','MGL','MOTHERSON','MPHASIS','MRF','NATIONALUM',
  'NAUKRI','NMDC','OIL','PHOENIXLTD','PIIND','POLICYBZR','PRESTIGE',
  'RBLBANK','RECLTD','SOLARINDS','SRF','STARHEALTH','SUNDARMFIN',
  'SUPREMEIND','SUZLON','TATACHEM','TATACOMM','TATAELXSI','TIINDIA',
  'TORNTPOWER','TRIDENT','UNOMINDA','VBL','YESBANK','GSPL',
];

export const UNIVERSE = [...new Set([...NIFTY50, ...NIFTY_NEXT50, ...NIFTY_MIDCAP])];

export function indexOf(sym) {
  if (NIFTY50.includes(sym))      return 'Nifty50';
  if (NIFTY_NEXT50.includes(sym)) return 'Next50';
  return 'MidCap';
}
